// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjLdl1YWyqXisMpsorowXPU062fZYb9zA',
    appId: '1:251528458795:web:10677d6f8398187375306e',
    messagingSenderId: '251528458795',
    projectId: 'sealtech-11470',
    authDomain: 'sealtech-11470.firebaseapp.com',
    storageBucket: 'sealtech-11470.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdpSZv1no4Wlfb0yIpgtDm7okafnBJ6FU',
    appId: '1:251528458795:android:c6c3779c6ba85b3e75306e',
    messagingSenderId: '251528458795',
    projectId: 'sealtech-11470',
    storageBucket: 'sealtech-11470.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3yX9qpY0CiqOXPwnwW5OOxe_hKqbcjm8',
    appId: '1:251528458795:ios:4d522eb3f0ead04f75306e',
    messagingSenderId: '251528458795',
    projectId: 'sealtech-11470',
    storageBucket: 'sealtech-11470.appspot.com',
    iosBundleId: 'com.example.sealtech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3yX9qpY0CiqOXPwnwW5OOxe_hKqbcjm8',
    appId: '1:251528458795:ios:5718031c10b6fe6c75306e',
    messagingSenderId: '251528458795',
    projectId: 'sealtech-11470',
    storageBucket: 'sealtech-11470.appspot.com',
    iosBundleId: 'com.example.sealtech.RunnerTests',
  );
}
