// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc0JKG4U5jE51XdExepa-V_D_LGdGgzas',
    appId: '1:792940813419:web:33d7551cc419ddef6da52e',
    messagingSenderId: '792940813419',
    projectId: 'sealtech-366c0',
    authDomain: 'sealtech-366c0.firebaseapp.com',
    storageBucket: 'sealtech-366c0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ6yYAjn7KHk0oNxKkyaZDEiL4R8Ujstc',
    appId: '1:792940813419:android:ccbee07145e761b96da52e',
    messagingSenderId: '792940813419',
    projectId: 'sealtech-366c0',
    storageBucket: 'sealtech-366c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMZDKewPFM_yxnY5a5BXDJpF-8Qd1do5s',
    appId: '1:792940813419:ios:85c188d432e6640a6da52e',
    messagingSenderId: '792940813419',
    projectId: 'sealtech-366c0',
    storageBucket: 'sealtech-366c0.appspot.com',
    iosBundleId: 'com.example.sealtech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMZDKewPFM_yxnY5a5BXDJpF-8Qd1do5s',
    appId: '1:792940813419:ios:5ebe1d13577a4c616da52e',
    messagingSenderId: '792940813419',
    projectId: 'sealtech-366c0',
    storageBucket: 'sealtech-366c0.appspot.com',
    iosBundleId: 'com.example.sealtech.RunnerTests',
  );
}
